# Generated by Django 3.1.6 on 2021-05-18 20:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('windscreen_coverage', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('passenger_liability_coverage', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('flood_coverage', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('windstorm_coverage', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('landslide_coverage', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('subsidence_coverage', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('create_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
