# Generated by Django 3.1.6 on 2021-05-18 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_quotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=80, verbose_name='Vehicle Model')),
                ('number', models.CharField(max_length=40, verbose_name='Vehicle No.')),
                ('year_make', models.CharField(max_length=40, verbose_name='Vehicle Year Make')),
                ('price', models.DecimalField(decimal_places=2, default=100000.0, max_digits=12, verbose_name='Vehicle Price')),
            ],
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='quotation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.quotation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotation',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.vehicle'),
            preserve_default=False,
        ),
    ]
