# Generated by Django 3.1.6 on 2021-05-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_coveragesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.quotation'),
        ),
    ]
